# for module compiling
import os
from building import *

objs = []
cwd  = GetCurrentDir()
list = os.listdir(cwd)

if GetDepend('PKG_USING_OPENMV_CP'):
    for item in list:
        if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
            objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
